# .github/workflows/sast-scan.yml

name: Python SAST Security Scan with Bandit

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]
  workflow_dispatch:

jobs:
  bandit-scan:
    runs-on: ubuntu-latest

    # Устанавливаем рабочую директорию по умолчанию для всех шагов этой задачи
    defaults:
      run:
        working-directory: ./TODO-List-Back

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit
          # Если для анализа нужны зависимости проекта, можно их установить
          # pip install -r requirements.txt

      - name: Run Bandit Scan
        run: bandit -r . -c bandit.yml --exit-code 1